---
title: "p8105_hw2_tj2519"
output: github_document
date: "2023-09-30"
---
```{r}
library(tidyverse)
```


# Problem 1 - process the pols-month, snp, unemployment dataset
```{r}
pols_df = 
  read_csv("data/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, c("year", "month", "day"), "-") %>% 
  mutate(month = ifelse(month == "01", "jan", month),
         month = ifelse(month == "02", "feb", month),
         month = ifelse(month == "03", "mar", month),
         month = ifelse(month == "04", "apr", month),
         month = ifelse(month == "05", "may", month),
         month = ifelse(month == "06", "jun", month),
         month = ifelse(month == "07", "jul", month),
         month = ifelse(month == "08", "aug", month),
         month = ifelse(month == "09", "sep", month),
         month = ifelse(month == "10", "oct", month),
         month = ifelse(month == "11", "nov", month),
         month = ifelse(month == "12", "dec", month)
         ) %>% 
  mutate(president = ifelse(prez_gop == 1, "gop", "dem")) %>% 
  select(-day, -starts_with("prez"))

print(sapply(pols_df, class))
view(pols_df)



snp_df = 
  read_csv("data/snp.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date(date, format = "%m/%d/%y")) %>% 
  separate(date, c("year", "month", "day"), "-") %>% 
  mutate(year = as.numeric(year), month = as.numeric(month)) %>% 
  mutate(year = ifelse(year > as.integer(format(Sys.Date(), "%Y")), 
                       year - 100, year)) %>% 
  arrange(year, month) %>% 
  mutate(month = ifelse(month == 1, "jan", month),
         month = ifelse(month == 2, "feb", month),
         month = ifelse(month == 3, "mar", month),
         month = ifelse(month == 4, "apr", month),
         month = ifelse(month == 5, "may", month),
         month = ifelse(month == 6, "jun", month),
         month = ifelse(month == 7, "jul", month),
         month = ifelse(month == 8, "aug", month),
         month = ifelse(month == 9, "sep", month),
         month = ifelse(month == 10, "oct", month),
         month = ifelse(month == 11, "nov", month),
         month = ifelse(month == 12, "dec", month)
         ) %>%
  select(-day)
  
print(sapply(snp_df, class))
view(snp_df)


unemployment_df = 
  read_csv("data/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "percent"
  )
  


view(unemployment_df)
```

